/* Guilherme Cezarino Freire RA: 1902214
   Caique Alba Buttigon RA: 1901537
   Iran Luiz dos Santos Junior RA: 1902358
   Israel Felipe Eduardo da Silva RA: 1900940
   Pedro Botter Bondezan RA: 1901567
   */	


CREATE DATABASE BD_AC3

CREATE TABLE ATENDENTE (
CPF VARCHAR (15) NOT NULL,
NOME VARCHAR(50) NOT NULL,
SALARIO FLOAT CHECK (SALARIO>=1045.0),

CONSTRAINT PK_CPF_ATENDENTE PRIMARY KEY (CPF)
)

CREATE TABLE MANOBRISTA (
CNH VARCHAR (20) NOT NULL,
NOME VARCHAR (50) NOT NULL,
SALARIO FLOAT CHECK (SALARIO>=1045.0),

CONSTRAINT PK_CNH_MANOBRISTA PRIMARY KEY (CNH)
)

CREATE TABLE VAGA (
LOCALIZACAO VARCHAR (10) NOT NULL,
SITUACAO VARCHAR (7) CHECK (SITUACAO ='Ocupada' or SITUACAO = 'Livre')
DEFAULT 'Livre',

CONSTRAINT PK_LOCALIZACAO_VAGA PRIMARY KEY (LOCALIZACAO)
)

CREATE TABLE CLIENTE (
CPF VARCHAR (15) NOT NULL,
NOME VARCHAR (50) NOT NULL,
CPF_ATEND_CADASTRO VARCHAR (15),
DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 

CONSTRAINT PK_CPF_CLIENTE PRIMARY KEY (CPF),
CONSTRAINT FK_CPF_ATEND_CADASTRO FOREIGN KEY (CPF_ATEND_CADASTRO)
REFERENCES ATENDENTE (CPF)
)

CREATE TABLE VEICULO (
PLACA VARCHAR (12) NOT NULL,
CPF_CLIENTE VARCHAR (15),
MODELO VARCHAR (20) NOT NULL,
COR VARCHAR (10),

CONSTRAINT PK_PLACA_VEICULO PRIMARY KEY (PLACA),
CONSTRAINT FK_CPF_CLIENTE_VEICULO FOREIGN KEY (CPF_CLIENTE)
REFERENCES CLIENTE (CPF)
)

CREATE TABLE LOCACAO (
CPF_CLIENTE VARCHAR(15),
LOCAL_VAGA VARCHAR (10),
DATA_HORA_ENTRADA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATA_HORA_SAIDA DATETIME,
VALOR FLOAT CHECK (VALOR >= 10.0),

CONSTRAINT PK_CPF_CLIENTE_E_LOCAL_VAGA PRIMARY KEY (CPF_CLIENTE , LOCAL_VAGA),

CONSTRAINT FK_CPF_CLIENTE_LOCACAO FOREIGN KEY (CPF_CLIENTE)
REFERENCES CLIENTE (CPF),

CONSTRAINT FK_LOCAL_VAGA_LOCACAO FOREIGN KEY (LOCAL_VAGA)
REFERENCES VAGA (LOCALIZACAO)
)

CREATE TABLE MANOBRA (
CNH_MANOBRISTA VARCHAR (20),
PLACA_VEICULO VARCHAR (12),
DATA_HORA_MANOBRA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT PK_CNH_PLACA_HORARIO_MANOBRA PRIMARY KEY (CNH_MANOBRISTA,
PLACA_VEICULO, DATA_HORA_MANOBRA),

CONSTRAINT FK_PLACA_VEICULO_MANOBRA FOREIGN KEY (PLACA_VEICULO)
REFERENCES VEICULO (PLACA),

CONSTRAINT FK_CNH_MANOBRISTA_MANOBRA FOREIGN KEY (CNH_MANOBRISTA)
REFERENCES MANOBRISTA (CNH)
)